### ISSUE TITLE
paged component throws error

### ISSUE THREAD

**Issue by Kukks** [SpoonX/aurelia-orm#269]
Attempted to use the `paged` component exactly as listed in the docs and got this:

```
vendor-bundle.js:14418 ERROR [app-router] TypeError: Cannot read property 'getRepository' of undefined
    at Paged.resourceChanged (http://localhost:9000/node_modules/aurelia-orm/dist/amd/component/paged.js:130:43)
    at BehaviorPropertyObserver.selfSubscriber (http://localhost:9000/scripts/vendor-bundle.js:22559:48)
    at BehaviorPropertyObserver.call (http://localhost:9000/scripts/vendor-bundle.js:22425:14)
    at BindableProperty._initialize (http://localhost:9000/scripts/vendor-bundle.js:22600:22)
    at new Controller (http://localhost:9000/scripts/vendor-bundle.js:22233:23)
    at HtmlBehaviorResource.create (http://localhost:9000/scripts/vendor-bundle.js:22918:24)
    at applyInstructions (http://localhost:9000/scripts/vendor-bundle.js:21066:33)
    at ViewFactory.create (http://localhost:9000/scripts/vendor-bundle.js:21287:9)
    at HtmlBehaviorResource.create (http://localhost:9000/scripts/vendor-bundle.js:22929:41)
    at http://localhost:9000/scripts/vendor-bundle.js:27012:51
From previous event:
    at RouterView.process (http://localhost:9000/scripts/vendor-bundle.js:27003:95)
    at _loop (http://localhost:9000/scripts/vendor-bundle.js:17202:31)
    at NavigationInstruction._commitChanges (http://localhost:9000/scripts/vendor-bundle.js:17217:9)
    at http://localhost:9000/scripts/vendor-bundle.js:17204:69
    at <anonymous>
From previous event:
    at _loop (http://localhost:9000/scripts/vendor-bundle.js:17202:72)
    at NavigationInstruction._commitChanges (http://localhost:9000/scripts/vendor-bundle.js:17217:9)
    at CommitChangesStep.run (http://localhost:9000/scripts/vendor-bundle.js:17069:36)
    at next (http://localhost:9000/scripts/vendor-bundle.js:17038:20)
    at iterate (http://localhost:9000/scripts/vendor-bundle.js:18148:14)
    at processActivatable (http://localhost:9000/scripts/vendor-bundle.js:18151:12)
    at ActivateNextStep.run (http://localhost:9000/scripts/vendor-bundle.js:18032:14)
    at next (http://localhost:9000/scripts/vendor-bundle.js:17038:20)
    at iterate (http://localhost:9000/scripts/vendor-bundle.js:18061:14)
    at processDeactivatable (http://localhost:9000/scripts/vendor-bundle.js:18064:12)
    at DeactivatePreviousStep.run (http://localhost:9000/scripts/vendor-bundle.js:18020:14)
    at next (http://localhost:9000/scripts/vendor-bundle.js:17038:20)
    at iterate (http://localhost:9000/scripts/vendor-bundle.js:18148:14)
    at processActivatable (http://localhost:9000/scripts/vendor-bundle.js:18151:12)
    at CanActivateNextStep.run (http://localhost:9000/scripts/vendor-bundle.js:18008:14)
From previous event:
    at LoadRouteStep.run (http://localhost:9000/scripts/vendor-bundle.js:18295:68)
    at next (http://localhost:9000/scripts/vendor-bundle.js:17038:20)
    at iterate (http://localhost:9000/scripts/vendor-bundle.js:18061:14)
    at processDeactivatable (http://localhost:9000/scripts/vendor-bundle.js:18064:12)
    at CanDeactivatePreviousStep.run (http://localhost:9000/scripts/vendor-bundle.js:17996:14)
    at next (http://localhost:9000/scripts/vendor-bundle.js:17038:20)
    at http://localhost:9000/scripts/vendor-bundle.js:17487:16
From previous event:
    at BuildNavigationPlanStep.run (http://localhost:9000/scripts/vendor-bundle.js:17485:58)
    at next (http://localhost:9000/scripts/vendor-bundle.js:17038:20)
    at Pipeline.run (http://localhost:9000/scripts/vendor-bundle.js:17051:14)
    at http://localhost:9000/scripts/vendor-bundle.js:18624:25
From previous event:
    at AppRouter._dequeueInstruction (http://localhost:9000/scripts/vendor-bundle.js:18597:32)
    at AppRouter.activate (http://localhost:9000/scripts/vendor-bundle.js:18574:12)
    at http://localhost:9000/scripts/vendor-bundle.js:18544:31
    at <anonymous>
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:18543:24
    at http://localhost:9000/scripts/vendor-bundle.js:18549:16
    at AppRouter.registerViewPort (http://localhost:9000/scripts/vendor-bundle.js:18556:10)
    at new RouterView (http://localhost:9000/scripts/vendor-bundle.js:26961:19)
    at Object.invokeWithDynamicDependencies (http://localhost:9000/scripts/vendor-bundle.js:12398:20)
    at InvocationHandler.invoke (http://localhost:9000/scripts/vendor-bundle.js:12380:168)
    at Container.invoke (http://localhost:9000/scripts/vendor-bundle.js:12644:25)
    at ProviderResolver.get (http://localhost:9000/scripts/vendor-bundle.js:20909:74)
    at Container.get (http://localhost:9000/scripts/vendor-bundle.js:12583:23)
    at Container.elementContainerGet [as get] (http://localhost:9000/scripts/vendor-bundle.js:20964:17)
    at HtmlBehaviorResource.create (http://localhost:9000/scripts/vendor-bundle.js:22917:58)
    at applyInstructions (http://localhost:9000/scripts/vendor-bundle.js:21066:33)
    at ViewFactory.create (http://localhost:9000/scripts/vendor-bundle.js:21287:9)
    at HtmlBehaviorResource.create (http://localhost:9000/scripts/vendor-bundle.js:22929:41)
    at http://localhost:9000/scripts/vendor-bundle.js:23351:18
From previous event:
    at CompositionEngine.createController (http://localhost:9000/scripts/vendor-bundle.js:23350:10)
    at CompositionEngine._createControllerAndSwap (http://localhost:9000/scripts/vendor-bundle.js:23316:19)
    at CompositionEngine.compose (http://localhost:9000/scripts/vendor-bundle.js:23396:21)
    at TemplatingEngine.compose (http://localhost:9000/scripts/vendor-bundle.js:23664:38)
    at Aurelia.setRoot (http://localhost:9000/scripts/vendor-bundle.js:13096:21)
    at http://localhost:9000/scripts/app-bundle.js:78:28
From previous event:
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:77:25)
    at http://localhost:9000/scripts/vendor-bundle.js:11928:22
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:11923:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:11914:12)
    at http://localhost:9000/scripts/vendor-bundle.js:11947:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:11945:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:11944:29
    at <anonymous>
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:11940:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:11967:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5892:33)
    at Module.check (http://localhost:9000/scripts/vendor-bundle.js:5080:51)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:5372:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5753:39)
    at Module.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:5357:33)
    at http://localhost:9000/scripts/vendor-bundle.js:4333:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:4258:31)
    at Module.enable (http://localhost:9000/scripts/vendor-bundle.js:5309:17)
    at Module.init (http://localhost:9000/scripts/vendor-bundle.js:4985:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5656:36
```

**Comment by RWOverdijk** [comment]
Fixed.

I'll publish this soon.

**Comment by Kukks** [comment]
Nice!
