### ISSUE TITLE
Issue with latest webpack skeleton

### ISSUE THREAD

**Issue by Kukks** [SpoonX/aurelia-orm#287]
upon initializing aurelia orm(`  .plugin(PLATFORM.moduleName("aurelia-orm"), ()=>{})`) in the latest webpack skeleton, you get this error:

```
Error: Unable to find module with ID: aurelia-validation/validate-binding-behavior
    at WebpackLoader.<anonymous> (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9506:35)
    at step (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9355:23)
    at Object.next (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9336:53)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9330:71
    at 150.__awaiter (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9326:12)
    at WebpackLoader.150.WebpackLoader._import (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9471:16)
    at WebpackLoader.<anonymous> (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9571:44)
    at step (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9355:23)
    at Object.next (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9336:53)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9330:71
From previous event:
    at 150.__awaiter (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9326:12)
    at WebpackLoader.150.WebpackLoader.loadModule (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9558:16)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9549:65
    at Array.map (native)
    at WebpackLoader.150.WebpackLoader.loadAllModules (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9549:32)
    at ViewEngine.importViewResources (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:26931:24)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46240:23
From previous event:
    at loadResources (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46231:7)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46308:14
    at next (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46188:30)
    at runTasks (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46194:10)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46474:16
From previous event:
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46473:21
From previous event:
    at FrameworkConfiguration.apply (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46458:42)
    at Aurelia.start (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:46074:37)
    at Object.<anonymous> (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:52424:50)
    at step (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:52347:23)
    at Object.next (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:52328:53)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:52322:71
From previous event:
    at main.__awaiter (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:52318:12)
    at Object.configure (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:52366:12)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9220:27
From previous event:
    at config (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9215:54)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9251:12
From previous event:
    at bootstrap (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9250:24)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9237:7
From previous event:
    at run (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9232:59)
    at Object.<anonymous> (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9257:16)
    at Object.149 (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:9258:30)
    at __webpack_require__ (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:50:30)
    at Object.225 (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:17217:18)
    at __webpack_require__ (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:50:30)
    at 0.module.exports.ctor.super_ (http://localhost:8080/app.2b398ae46c359f295998.bundle.js:147:18)
    at http://localhost:8080/app.2b398ae46c359f295998.bundle.js:150:10
```

**Comment by Kukks** [comment]
As a workaround I added this config to the webpack config:
```
    new ModuleDependenciesPlugin({
      "aurelia-orm": [
        "./component/association-select",
        "./component/view/bootstrap/association-select.html",
        "./component/view/bootstrap/paged.html",
        "./component/paged"]
    }),
```

and also this after my aurelia configuration:
```

  PLATFORM.moduleName("aurelia-validation/validate-binding-behavior");
  PLATFORM.moduleName("aurelia-validation/validation-errors-custom-attribute");
  PLATFORM.moduleName("aurelia-validation/validation-renderer-custom-attribute");
```

**Comment by RWOverdijk** [comment]
Same question here, mind submitting a PR for this?

**Comment by gregoryagu** [comment]
I am also getting this issue. The work-around was as @Kukks states, adding this to the `plugins` section of webpack config:

```
plugins: [
...
new ModuleDependenciesPlugin({
      "aurelia-orm": [
        "./component/association-select",
        "./component/view/bootstrap/association-select.html",
        "./component/view/bootstrap/paged.html",
        "./component/paged"]
    }),
```
