### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by mreiche** [SpoonX/aurelia-orm#299]
When I register my entity like described here (https://aurelia-orm.spoonx.org/api_entitymanager.html)
```javascript
import {Entity, validatedResource, association,type} from 'aurelia-orm';

export class Client extends Entity {
	@type('string')
	name = null;
}
```
with
```javascript
import Client from '../services/client';
constructor(em:EntityManager) {
		em.registerEntity(Client);
}
```
I get the error message
```
myty-aurelia.dev.js:8820 ERROR [app-router] Error: Error invoking ClientsManager. Check the inner error for details.
------------------------------------------------
Inner Error:
Message: Cannot read property 'name' of undefined
Inner Error Stack:
TypeError: Cannot read property 'name' of undefined
    at Function.forTarget (http://localhost:9000/3rdParty/jspm_packages/npm/aurelia-orm@6.1.2/aurelia-orm.js:262:93)
    at EntityManager.registerEntity (http://localhost:9000/3rdParty/jspm_packages/npm/aurelia-orm@6.1.2/aurelia-orm.js:913:30)
    at new ClientsManager (http://localhost:9000/tycon/modules/clients/components/manager.js!transpiled:36:9)
```

**Comment by mreiche** [comment]
The examples are wrong. You have to write
```javascript
import {Client} from '../services/client';
```
This is a documentation bug in https://aurelia-orm.spoonx.org/api_entitymanager.html

**Comment by RWOverdijk** [comment]
@mreiche Nice catch. Yes, if you use named exports, you need to use named imports.
