### ISSUE TITLE
Error: A BindingLanguage must implement parseText(...)

### ISSUE THREAD

**Issue by devenson** [SpoonX/aurelia-orm#74]
Using aurelia-orm installing today we are getting this error. Changing the dependency for aurelia-templating to 1.2.1 it worked fine. So there is some incompatibility with 1.2.2.

```
DEBUG [templating] importing resources for http://localhost:9000/jspm_packages/npm/aurelia-orm@2.2.3/component/association-select.html []
aurelia-templating.js:692 Uncaught (in promise) Error: A BindingLanguage must implement parseText(...)
    at BindingLanguage.parseText (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:692:13)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:2008:79)
    at ViewCompiler._compileNode (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:2028:33)
    at ViewCompiler.compile (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:1985:12)
    at eval (http://localhost:9000/jspm_packages/npm/aurelia-templating@1.0.0-beta.1.2.2/aurelia-templating.js:2615:49)
```

**Comment by doktordirk** [comment]
can you recheck for any forks?

**Comment by doktordirk** [comment]
pretty sure it's from forks as i got exactly that error then. closing for now, but do tell if loosing forks didn't fix it for you

**Comment by devenson** [comment]
Hey, sorry. I meant to respond to this and got side-tracked. I think you're right. We've managed to get everything updated to the latest.

**Comment by doktordirk** [comment]
well, good to hear :smile:
